umcrunner new commands and clean up

diff --git a/bin/umcrunner b/bin/umcrunner
--- a/bin/umcrunner
+++ b/bin/umcrunner
@@ -15,45 +15,51 @@ source ~/umc/bin/umc.h  >/dev/null
 # script directory
 scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
+# exit this script from within a function
+trap "exit 1" TERM
+export TOP_PID=$$
 
 function print_usage () {
-    echo "umcrunner runs an instance of umc tool and logs its output to files according to time rotation definition."
+    echo "Runs and queries umc instances running on a single host."
     echo ""
     echo "Usage:"
     echo "  * running an instance of an umc tool and store logs in $UMC_LOG_DIR/<id>:"
     echo "  umcrunner --run <id> <rotate-time> <tool> <delay> <count> [<umc-params>]"
     echo ""
     echo "  where:"
-    echo "  id           A unique id of umc tool instance"
-    echo "  rotate-time  The time to rotate the umc output log"
-    echo "  tool         umc tool id"
-    echo "  delay        Delay in seconds between umc tool runs"
-    echo "  count        Number of umc tool runs"
-    echo "  umc-params   Additional umc tool paramers"
+    echo "  id               A unique id of umc tool instance"
+    echo "  rotate-time      The time to rotate the umc output log"
+    echo "  tool             umc tool id"
+    echo "  delay            Delay in seconds between umc tool runs"
+    echo "  count            Number of umc tool runs"
+    echo "  umc-params       Additional umc tool paramers"
     echo ""
     echo "  * other usages:"
-    echo "  umcrunner --stats [--noheader] | --stopall | --stop <id> | --gpid <id>"
+    echo "  umcrunner --help | --stats [--noheader] | --runall <file> | --stopall | --stop <id> | --list <id>"
     echo ""
     echo "  where:"
-    echo "  --stats     displayes all running umc instances"
-    echo "  --noheader  suppress the header in stats"
-    echo "  --stopall   stops all running umc instances"
-    echo "  --stop <id> stops the instance"
-    echo "  --gpid <id> prints group process id"
+    echo "  --help           this help"
+    echo "  --stats          displays all running umc instances (see further below what it shows)"
+    echo "  --noheader       suppress the header in stats"
+    echo "  --runall <file>  runs all umc instances from a definition file <file>"    
+    echo "  --stopall        stops all running umc instances"
+    echo "  --stop <id>      stops an umc instance"
+    echo "  --ls <id>        runs 'ls -all' in the umc instance directory"
+    echo "  --ps <id>        shows a process hierarchy of the umc instnace"
     echo ""
     echo "  umcrunner --stats displays following detailed information about running umc instances:"
     echo ""
-    echo "  GPID        group process ID"
-    echo "  UMC_ID      unique umc instance ID"
-    echo "  ROTAT_T     roation time in seconds used as a value for logdirector.pl -timeLimit"
-    echo "  UMC         umc tool (sensor) id"
-    echo "  DELAY       umc delay value"
-    echo "  COUNT       umc count value"
-    echo "  PARAMS      additional parameters of umc tool (umc tool specific)"
-    echo "  STARTED     time the umc instance was started"
-    echo "  RUN_T       umc instance running time"
-    echo "  CPU_T       cpu time consumed by the umc instance since its start up"
-    echo "  BACKLOG     number of files in a backlog (in a directory $UMC_LOG_DIR/<UMC_ID>)"
+    echo "  GPID             group process ID"
+    echo "  UMC_ID           unique umc instance ID"
+    echo "  ROTAT_T          roation time in seconds used as a value for logdirector.pl -timeLimit"
+    echo "  UMC              umc tool (sensor) id"
+    echo "  DELAY            umc tool delay value"
+    echo "  COUNT            umc tool count value"
+    echo "  PARAMS           additional parameters of umc tool (umc tool specific)"
+    echo "  STARTED          time the umc instance was started"
+    echo "  RUN_T            umc instance running time"
+    echo "  CPU_T            cpu time consumed by the umc instance since its start up"
+    echo "  BACKLOG          number of files in a backlog (in a directory $UMC_LOG_DIR/<UMC_ID>)"
 }
 
 function umc_run() {
@@ -82,12 +88,18 @@ function umc_run() {
 
 function umc_gpid() {
      umc_id="$1" && shift
-     echo $(ps axf -o  "%p %r %y %x %a" | grep -v grep | egrep "logdirector\.pl.*$umc_id" | awk '{print $2}')
+     echo $(ps axf -o  "%p %r %y %x %a" | grep -v "grep" | egrep -v "$TOP_PID.+umcrunner" | egrep "umcrunner \-\-run $umc_id " | awk '{print $2}')
 }
 
-# returns a list of all umc runner IDs on this host
-function umc_allids() {
-    ps ax | grep logdirector.pl | egrep -o "\-name [a-zA-Z0-9\.\-]+" | awk '{print $2}'
+function umc_gpid_check () {
+    umc_id="$1" && shift
+    gpid=$(umc_gpid $umc_id)
+    if [ "$gpid" = "" ]; then
+        echo >&2 "umc instance with id $umc_id is not running!"
+        kill -s TERM $TOP_PID
+    else
+        echo $gpid
+    fi
 }
 
 # prints aligned umc stats row 
@@ -104,7 +116,7 @@ fi
 # the first argument is the command to run
 cmd=$1 && shift
 
-# *** run the new instance of the tool
+# *** run a new umc instance 
 if [ "$cmd" = "--run" ]; then
 
     # command parameters
@@ -124,7 +136,7 @@ if [ "$cmd" = "--run" ]; then
     # check if umc with the same id is already running
     gpid=$(umc_gpid "$umc_id")
     if [ "$gpid" != "" ]; then
-        #echo >&2 "umc with id $umc_id is already running (gpid=$gpid)!"
+        echo >&2 "umc with id $umc_id is already running (gpid=$gpid)!"
         exit 0
     fi
 
@@ -134,7 +146,7 @@ if [ "$cmd" = "--run" ]; then
     exit 0
 fi
 
-# *** stop the instance of the tool
+# *** stop a currently running umc instance 
 if [ "$cmd" = "--stop" ]; then
     # command parameters
     umc_id=$1 && shift
@@ -149,20 +161,7 @@ if [ "$cmd" = "--stop" ]; then
     exit 0
 fi
 
-# get the instance information
-if [ "$cmd" = "--gpid" ]; then
-    # command parameters
-    umc_id=$1 && shift    
-
-    gpid=$(umc_gpid "$umc_id")
-    if [ "$gpid" != "" ]; then
-        echo $gpid   
-        exit 0
-    else
-        exit 1
-    fi
-fi
-
+# *** show stats for all umc instances running on this host
 if [ "$cmd" = "--stats" ]; then
     # command parameters
     args=$1 && shift
@@ -214,6 +213,7 @@ if [ "$cmd" = "--stats" ]; then
 
 fi
 
+# *** stop all umc instances on this host
 if [ "$cmd" = "--stopall" ]; then
     umcrunner --stats --noheader | awk '{ print $2 }' | \
     while read line; do
@@ -224,5 +224,65 @@ if [ "$cmd" = "--stopall" ]; then
     exit 0 
 fi
 
+# *** show directory listing of the umc instance
+if [ "$cmd" = "--ls" ]; then
+    # command parameters
+    umc_id=$1 && shift   
 
-print_usage
+    echo "Directory listing of $UMC_LOG_DIR/$umc_id"
+    ls -all $UMC_LOG_DIR/$umc_id
+    exit 0 
+fi
+
+# *** show process hierarchy of a umc instance
+if [ "$cmd" = "--ps" ]; then
+    # command parameters
+    umc_id=$1 && shift
+    gpid=$(umc_gpid_check $umc_id)
+
+    ps axf -eo pid,pgid,cputime,cmd | awk -v w=$(tput cols) -v gpid=$gpid '{if ($2==gpid || NR==1) print substr($0, 1, w)}'
+
+    exit 0 
+fi
+
+# *** run all umc instances from a definition file
+if [ "$cmd" = "--runall" ]; then
+    # command parameters
+    conf=$1 && shift    
+
+    # if conf cannot be found, try to find it in the umc/bin directroy
+    if [ ! -f $conf ]; then 
+        oconf=$conf
+        conf=$scriptDir/$conf; 
+        if [ ! -f $conf ]; then
+            echo >&2 "The configuration file $oconf cannot be found!"
+            exit 1
+        fi 
+    fi
+
+    # run all instances from this file
+    # setsid will ensure each umc instance wull run its own process group
+    cat $conf | grep -v "^$" | grep -v "^#" | \
+    while read line; do
+        setsid umcrunner --run $line 
+    done
+
+    exit 0 
+fi
+
+# *** show help
+if [ "$cmd" = "--help" ]; then
+    print_usage
+    exit 0
+fi
+
+# not a recognized command
+if [ "$cmd" = "" ]; then
+    echo >&2 "Specify a valid umcrunner command!"
+else
+    echo >&2 "$cmd is not recognized as a valid umcrunner command!"    
+fi
+
+echo >&2 "Run umcrunner --help for more information."
+exit 1
+
