small refactoring of vagrant scripts

diff --git a/test/oel-511/Vagrantfile b/test/oel-511/Vagrantfile
--- a/test/oel-511/Vagrantfile
+++ b/test/oel-511/Vagrantfile
@@ -21,43 +21,43 @@ Vagrant.configure("2") do |config|
     # set Europe/Prague timezone 
     sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Prague /etc/localtime
 
-    # install python 2.7.11 locally
-    echo "Installing python-2.7.11 locally, this will take few minutes..."
-    echo "Check python-2.7.11-install.log"
-    ~/umc/test/oel-511/python-2.7.11-install.sh &>~/umc/test/oel-511/python-2.7.11-install.log
-    if [ $? != 0 ]; then
-    	echo >&2 "Error when installing python 2.7.11 locally, check ~/umc/test/oel-511/python-2.7.11-install.log for details"
-    fi
+    # install a library
+    install_lib () {
+    	echo "Installing $1 locally..."
+        echo "Check $1-install.log"
+        mkdir -p ~/umc/test/oel-511/logs
+        ~/umc/test/oel-511/$1-install.sh &>~/umc/test/oel-511/logs/$1-install.log
+        if [ $? != 0 ]; then
+           echo >&2 "Error when installing $1, check ~/umc/test/oel-511/logs/$1-install.log for details"
+        fi
+    }
 
-    # install jdk locally
-    echo "Installing jdk-8u162 locally..."
-    echo "Check jdk-8u162-install.log"
-    ~/umc/test/oel-511/jdk-8u162-install.sh &>~/umc/test/oel-511/jdk-8u162-install.log
-    if [ $? != 0 ]; then
-      echo >&2 "Error when installing jdk-8u162 locally, check ~/umc/test/oel-511/jdk-8u162-install.log for details"
-    fi
+    # writes a line to bash_profile
+    w2p () {
+	echo $1 >>~/.bash_profile
+    }
 
-    # install sqlcl locally
-    echo "Installing sqlcl-17.4.0 locally..."
-    echo "Check sqlcl-17.4.0-install.log"
-    ~/umc/test/oel-511/sqlcl-17.4.0-install.sh &>~/umc/test/oel-511/sqlcl-17.4.0-install.log
-    if [ $? != 0 ]; then
-      echo >&2 "Error when installing sqlcl 17.4.0 locally, check ~/umc/test/oel-511/sqlcl-17.4.0-install.log for details"
-    fi
+    # remove old logs directory 
+    rm -fr ~/umc/test/oel-511/logs
+
+    # install libraries
+    install_lib python-2.7.11
+    install_lib jdk-8u162
+    install_lib sqlcl-17.4.0
 
     # other settings on user login
-    echo "Setting up other settings on user logon" 
-    echo "" >>~/.bash_profile
-    echo "# various settings" >>~/.bash_profile
-    echo "export LS_COLORS=''" >>~/.bash_profile
-    echo "alias ll='ls -all --color=always'" >>~/.bash_profile
+    echo "Writing misc settings to bash_profile" 
+    w2p ""
+    w2p "# various settings" 
+    w2p "export LS_COLORS=''"
+    w2p "alias ll='ls -all --color=always'"
 
     # initialize umc on user login
-    echo "Setting up environment variables for umc"
-    echo "" >>~/.bash_profile
-    echo "# umc settings" >>~/.bash_profile
-    echo "source $HOME/umc/bin/umc.h &>/dev/null" >>~/.bash_profile
-    echo "umc" >>~/.bash_profile
+    echo "Writing umc settings to bash_profile"
+    w2p ""
+    w2p "# umc settings"
+    w2p "source $HOME/umc/bin/umc.h &>/dev/null"
+    w2p "umc"
 
   SHELL
   
